USE QLHTChuyenHang
GO

--TK: Stacey
--Pass: TK000002
SELECT * FROM SAN_PHAM

DECLARE @FLAG INT
EXEC @FLAG = USP_CAPNHAT_SP 'SP000006', 'LH000002', N'Bếp gas mini',''
IF @FLAG = 0
	PRINT N'CẬP NHẬT TÊN SẢN PHẨM THẤT BẠI'
ELSE
	PRINT N'CẬP NHẬT TÊN SẢN PHẨM THÀNH CÔNG'

SELECT * FROM SAN_PHAM