USE QLHTChuyenHang
GO

CREATE 
--ALTER
PROC USP_TIMSPTEN
	@TENSP NVARCHAR(100)
AS
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS(	SELECT * 
						FROM SAN_PHAM 
						WHERE TENSP LIKE '%' + @TENSP + '%')
		BEGIN
			PRINT @TENSP + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 
		END
		--ĐỂ TEST
		WAITFOR DELAY '0:0:05'
		---------
		SELECT * FROM SAN_PHAM WHERE TENSP LIKE '%' + @TENSP + '%'
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG ' + ERROR_MESSAGE()
		ROLLBACK TRAN
	END CATCH
COMMIT TRAN
GO

CREATE 
--ALTER
PROC USP_CAPNHAT_SP
	@MaSP CHAR(8),
	@MaLH CHAR(8),
	@TENCAPNHAT NVARCHAR(100),
	@Description NVARCHAR(500)
AS
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS ( SELECT * FROM SAN_PHAM WHERE MASP = @MaSP)
		BEGIN
			PRINT  N'SẢN PHẨM NÀY KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END

		IF @TENCAPNHAT IS NULL
		BEGIN
			PRINT  N'TÊN CẬP NHẬT KHÔNG ĐƯỢC TRỐNG'
			ROLLBACK TRAN
			RETURN 0
		END

		IF @TENCAPNHAT = ( SELECT TENSP FROM SAN_PHAM WHERE MASP = @MaSP)
		BEGIN
			PRINT  N'TÊN CẬP NHẬT KHÔNG ĐƯỢC TRÙNG VỚI TÊN CŨ'
			ROLLBACK TRAN
			RETURN 0
		END

		UPDATE SAN_PHAM SET TENSP = @TENCAPNHAT, MALH = @MaLH, MO_TA = @Description WHERE MASP = @MaSP
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG ' + ERROR_MESSAGE()
		ROLLBACK TRAN
		RETURN 0
	END CATCH
COMMIT TRAN
RETURN 1