-- Procedure --
USE QLHTChuyenHang
GO

-- THÊM CHI TIẾT ĐƠN HÀNG --
CREATE 
--ALTER 
PROC USP_THEM_CTDH 
@MADH CHAR(8), @MASP CHAR(8), @SL INT
AS
BEGIN
	DECLARE @THANH_TIEN MONEY
	SELECT @THANH_TIEN = (SELECT PP.GIA * @SL
						FROM PHAN_PHOI PP JOIN CHI_NHANH CN ON PP.MACN = CN.MACN
						JOIN DON_HANG DH ON DH.MADH = @MADH
						WHERE PP.MASP = @MASP AND DH.MADT = CN.MADT
						)
	INSERT CHI_TIET_DON_HANG(MADH, MASP, SO_LUONG, THANH_TIEN) VALUES (@MADH, @MASP, @SL, @THANH_TIEN)
	UPDATE DON_HANG
	SET DON_HANG.PHI_SAN_PHAM += @THANH_TIEN
	WHERE DON_HANG.MADH = @MADH
END
GO

-- UPDATE SỐ LƯỢNG SẢN PHẨM TRONG CHI TIẾT ĐƠN HÀNG -- 
CREATE 
--ALTER 
PROC USP_SUA_SOLUONG_CTDH
@MADH CHAR(8), @MASP CHAR(8), @SL_MOI INT
AS
BEGIN
	DECLARE @THANH_TIEN_MOI MONEY
	DECLARE @SL_CU INT, @THANH_TIEN_CU MONEY

	SET @SL_CU = (SELECT CTDH.SO_LUONG FROM CHI_TIET_DON_HANG CTDH WHERE CTDH.MADH = @MADH AND CTDH.MASP = @MASP)
	SET @THANH_TIEN_CU = (SELECT THANH_TIEN FROM CHI_TIET_DON_HANG CTDH WHERE CTDH.MADH = @MADH AND CTDH.MASP = @MASP)

	SET @THANH_TIEN_MOI = (SELECT PP.GIA * @SL_MOI
					FROM PHAN_PHOI PP JOIN CHI_NHANH CN ON PP.MACN = CN.MACN
					JOIN DON_HANG DH ON DH.MADH = @MADH
					WHERE PP.MASP = @MASP AND DH.MADT = CN.MADT
					)

	UPDATE CHI_TIET_DON_HANG SET SO_LUONG = @SL_MOI, THANH_TIEN = @THANH_TIEN_MOI WHERE MADH = @MADH AND MASP = @MASP

	UPDATE DON_HANG
	SET DON_HANG.PHI_SAN_PHAM += (@THANH_TIEN_MOI - @THANH_TIEN_CU)
	WHERE DON_HANG.MADH = @MADH
END
GO
-- GIA HẠN HỢP ĐỒNG (UPDATE THỜI HẠN TRONG BẢNG HOP_DONG) --
CREATE OR ALTER PROC USP_GIA_HAN_HOP_DONG
@MAHD CHAR(8), @NGAY_KY DATE, @NGAY_HET_HAN DATE
AS
BEGIN
	IF (@MAHD NOT IN (SELECT MAHD FROM HOP_DONG))
	BEGIN
		PRINT N'MAHD không tồn tại!'
		RETURN
	END
	DECLARE @STT INT
	SELECT @STT = ISNULL(MAX(STT),0)+1
    FROM LICH_SU_HOP_DONG
    WHERE MAHD = @MAHD
	INSERT LICH_SU_HOP_DONG VALUES(@MAHD, @STT, @NGAY_KY, @NGAY_HET_HAN)
	UPDATE HOP_DONG SET NGAY_KY = @NGAY_KY, NGAY_HET_HAN = @NGAY_HET_HAN
	WHERE MAHD = @MAHD
END

GO
-- THÊM HỢP ĐỒNG --> ĐỒNG THỜI LƯU VÀO BẢNG LỊCH SỬ HỢP ĐỒNG 
CREATE PROC USP_THEM_HOP_DONG
@MAHD CHAR(8), @MADT CHAR(8), @NGAY_KY DATE, @NGAY_HET_HAN DATE, @SO_CN_DK INT, @MSTHUE VARCHAR(20), @HOA_HONG DEC(5,4)
AS BEGIN
	IF (@SO_CN_DK > (SELECT SO_CHI_NHANH FROM DOI_TAC WHERE MADT = @MADT))
	BEGIN
		PRINT N'Số chi nhánh đăng ký > Tổng số chi nhánh của đối tác'
		RETURN
	END
	IF NOT EXISTS (SELECT MADT FROM DOI_TAC WHERE MADT = @MADT)
	BEGIN
		PRINT N'Không tồn tại đối tác!'
		RETURN
	END
	IF EXISTS(SELECT MADT FROM HOP_DONG WHERE MADT = @MADT)
	BEGIN
		PRINT N'Đối tác đã ký hợp đồng trước đó!'
		RETURN
	END
	INSERT HOP_DONG VALUES(@MAHD, @MADT, @NGAY_KY, @NGAY_HET_HAN, @SO_CN_DK, @MSTHUE, @HOA_HONG)
	INSERT LICH_SU_HOP_DONG VALUES(@MAHD, 1, @NGAY_KY, @NGAY_HET_HAN)
END

GO
-- CẬP NHẬT TRẠNG THÁI ĐƠN HÀNG --
CREATE PROC USP_UPDATE_TRANG_THAI_DH
@MADH CHAR(8), @TRANG_THAI NVARCHAR(20), @THOI_GIAN DATE
AS BEGIN
	IF NOT EXISTS (SELECT MADH FROM DON_HANG WHERE MADT = @MADH)
	BEGIN
		PRINT N'Không tồn tại đơn hàng!'
		RETURN
	END
	UPDATE DON_HANG SET TRANG_THAI = @TRANG_THAI WHERE MADH = @MADH
	INSERT TRANG_THAI_DON_HANG VALUES(@TRANG_THAI, @MADH, @THOI_GIAN)
END

GO
-- CẬP NHẬT SỐ LƯỢNG ĐƠN HÀNG CỦA ĐỐI TÁC --
CREATE PROC USP_UPDATE_SL_DON_DT
@MADT CHAR(8), @SL_DON INT
AS BEGIN
	IF (@SL_DON < (SELECT COUNT(*)
					FROM DON_HANG DH
					WHERE MADT = @MADT))
	BEGIN
		PRINT N'Số lượng đơn hàng đối tác bán ra đã vượt qua mức cho phép!'
		RETURN
	END

	UPDATE DOI_TAC SET SO_LUONG_DON = @SL_DON
END
---------------------------------------------
--TRIGGER TRÊN BẢNG CHI_TIET_DON_HANG CHO VIEC XÓA
GO
CREATE TRIGGER TG_TONGPHI_FOR_DELETE_CTDH
ON CHI_TIET_DON_HANG FOR DELETE
AS
BEGIN
	UPDATE DON_HANG
	SET DON_HANG.PHI_SAN_PHAM -= (SELECT SUM(deleted.THANH_TIEN)
							FROM deleted
							WHERE DON_HANG.MADH = deleted.MADH
							GROUP BY deleted.MADH
							)
	WHERE DON_HANG.MADH IN (SELECT DISTINCT MADH FROM deleted)
END

GO
-- 2. Số lượng đơn hàng bán ra không được vượt mức đăng ký của đối tác
CREATE TRIGGER TG_INSERT_UPDATE_DONHANG
ON DON_HANG FOR UPDATE, INSERT
AS
BEGIN
	IF EXISTS(SELECT * FROM inserted 
				JOIN DOI_TAC DT ON DT.MADT = inserted.MADT
				WHERE DT.SO_LUONG_DON < (SELECT COUNT(*)
												FROM DON_HANG DH
												WHERE inserted.MADT = DH.MADT
												)
				)
		BEGIN
			PRINT(N'Số lượng đơn hàng bán ra vượt mức đăng ký của đối tác!')
			ROLLBACK
		END
END