USE QLHTChuyenHang
GO
-- KHÁCH HÀNG XEM THÀNH TIỀN --
-- 'Keshi', 'TK000031'
DECLARE @FLAG INT
EXEC @FLAG = USP_KH_CTDH 'SP000010', 'CN000003', 2
IF @FLAG = 1
	PRINT N'CÓ LỖI XẢY RA!'
ELSE
	PRINT N'THÀNH TIỀN SẢN PHẨM'