USE QLHTChuyenHang
GO
-- KHÁCH HÀNG KIỂM TRA THÀNH TIỀN CỦA SẢN PHẨM
CREATE 
-- ALTER 
PROC USP_KH_CTDH
	@MaSP CHAR(8),
	@MaCN CHAR(8),
	@SoLuong INT
AS
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	BEGIN TRY
	IF @MaSP NOT IN (SELECT MASP FROM SAN_PHAM)
	BEGIN
		PRINT @MaSP + N' không tồn tại!!'
		ROLLBACK TRAN
		RETURN 1
	END
	IF @MaCN NOT IN (SELECT MACN FROM PHAN_PHOI)
	BEGIN
		PRINT @MaCN + N' không tồn tại / chưa ký hợp đồng!!'
		ROLLBACK TRAN
		RETURN 1
	END

	SELECT MASP, TENSP, @SoLuong AS SO_LUONG_MUA, GIA AS DON_GIA
	FROM UV_XEMSP_KH
	WHERE MASP = @MaSP AND MACN = @MaCN
	
	WAITFOR DELAY '0:0:05'

	SELECT GIA AS DON_GIA, @SoLuong AS SO_LUONG_MUA, GIA * @SoLuong AS THANH_TIEN
	FROM UV_XEMSP_KH
	WHERE MASP = @MaSP AND MACN = @MaCN

	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000);
		SELECT @ErrorMessage = ERROR_MESSAGE()
		RAISERROR(@ErrorMessage,16,1)
		ROLLBACK TRAN	
	END CATCH
COMMIT TRAN


GO
-- ĐỐI TÁC CẬP NHẬT GIÁ MỚI CHO SẢN PHẨM
CREATE 
--ALTER 
PROC USP_DT_SUAGIA
	@MaCN CHAR(8),
	@MaSP CHAR(8),
	@GiaMoi MONEY
AS
BEGIN TRAN
	BEGIN TRY
		IF @MaSP NOT IN (SELECT MASP
						FROM UV_SPDOITAC)
		BEGIN
			PRINT @MaSP + N' không phải mặt hàng của đối tác!!'
			ROLLBACK TRAN
			RETURN 1
		END
		IF @MaCN NOT IN (SELECT MACN
						FROM UV_CN_DOITAC
						WHERE MAHD IS NOT NULL)
		BEGIN
			PRINT @MaCN + N' không tồn tại / không thuộc quản lý của đối tác / chưa được ký hợp đồng!!'
			ROLLBACK TRAN
			RETURN 1
		END

		UPDATE UV_SPDOITAC SET GIA = @GiaMoi WHERE MASP = @MaSP AND MACN = @MaCN
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000);
		SELECT @ErrorMessage = ERROR_MESSAGE()
		RAISERROR(@ErrorMessage,16,1)
		ROLLBACK TRAN	
	END CATCH
COMMIT TRAN

