USE QLHTChuyenHang
GO

CREATE 
--ALTER
PROC USP_THEMPHIEUGIAOHANGTX
	@MADH CHAR(8),
	@NGAYGIAO DATE
AS
BEGIN TRAN
	BEGIN TRY
		INSERT PHIEU_GIAO_HANG VALUES ((SELECT TT.MATX FROM UV_TTTAIXE TT), @MADH, @NGAYGIAO) 
		--ĐỂ TEST
		WAITFOR DELAY '0:0:05'
		IF NOT EXISTS(	SELECT *
						FROM UV_DHTAIXE
						WHERE MADH = @MADH)
		BEGIN
			PRINT @MADH + N' ĐƠN HÀNG NÀY KHÔNG THUỘC KHU VỰC CỦA TÀI XẾ'
			ROLLBACK TRAN
			RETURN 0
		END
		IF @NGAYGIAO IS NULL OR @NGAYGIAO < (SELECT MAX(THOI_GIAN) FROM TRANG_THAI_DON_HANG WHERE @MADH = MADH)
		BEGIN
			PRINT N'KIỂM TRA LẠI NGÀY GIAO HÀNG (KHÔNG ĐƯỢC TRỐNG/ NGÀY GIAO KHÔNG HỢP LỆ)'
			ROLLBACK TRAN
			RETURN 0
		END
		--ROLLBACK TRAN 
		--RETURN 0
		-----
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG ' + ERROR_MESSAGE()
		ROLLBACK TRAN
		RETURN 0
	END CATCH
COMMIT TRAN
RETURN 1
GO

CREATE --ALTERPROC USP_KIEMTRADONHANGTX	@MADHCANTIM CHAR(8)ASSET TRAN ISOLATION LEVEL READ UNCOMMITTEDBEGIN TRAN	BEGIN TRY		IF @MADHCANTIM IS NULL
		BEGIN
			PRINT N'MÃ ĐƠN HÀNG TÌM KIẾM KHÔNG ĐƯỢC ĐỂ TRỐNG'
			ROLLBACK TRAN
			RETURN
		END		IF NOT EXISTS(	SELECT *
						FROM UV_DHTAIXE
						WHERE MADH = @MADHCANTIM)
		BEGIN
			PRINT @MADHCANTIM + N'ĐƠN HÀNG NÀY KHÔNG THUỘC KHU VỰC CỦA TÀI XẾ'
			ROLLBACK TRAN
			RETURN
		END		SELECT *
		FROM UV_DHTAIXEDANHAN
		WHERE MADH = @MADHCANTIM 	END TRY	BEGIN CATCH		PRINT N'LỖI HỆ THỐNG ' + ERROR_MESSAGE()		ROLLBACK TRAN	END CATCHCOMMIT TRANGO