USE QLHTChuyenHang
GO

-- GRANT EXEC TO KHACH_HANG
CREATE PROC USP_KH_TIMSP
	@TenSP NVARCHAR(100)
AS
BEGIN TRAN
	BEGIN TRY
	SELECT COUNT(*) AS SL_TIM_KIEM FROM UV_XEMSP_KH
	WHERE TENSP = @TenSP

	WAITFOR DELAY '0:0:05'

	SELECT * FROM UV_XEMSP_KH
	WHERE TENSP = @TenSP

	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1	
	END CATCH
COMMIT TRAN
RETURN 0

GO
CREATE PROC USP_DT_THEMSP
	@MaCN CHAR(8),
	@MaSP CHAR(8),
	@SL_Ton INT,
	@Gia MONEY
AS
--SET TRAN ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	BEGIN TRY
		IF @MaSP NOT IN (SELECT MASP
						FROM SAN_PHAM)
		BEGIN
			PRINT @MaSP + N' không tồn tại!!'
			ROLLBACK TRAN
			RETURN 1
		END
		IF @MaCN NOT IN (SELECT MACN
						FROM UV_CN_DOITAC
						WHERE MAHD IS NOT NULL)
		BEGIN
			PRINT @MaCN + N' không tồn tại / không thuộc quản lý của đối tác / chưa được ký hợp đồng!!'
			ROLLBACK TRAN
			RETURN 1
		END

		/*DECLARE @TenSP NVARCHAR(100), @MaLH CHAR(8), @MoTa NVARCHAR(500)
		SELECT @TenSP = TENSP, @MaLH = MALH, @MoTa = MO_TA
		FROM SAN_PHAM
		WHERE MASP = @MaSP */

		INSERT PHAN_PHOI
		VALUES (@MaSP, @MaCN, @SL_Ton, @Gia)

	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0

GO
-- CẤP QUYỀN THỰC THI PROC CHO ĐỐI TÁC VÀ TÀI XẾ
-- GRANT EXEC ON DOI_TAC

--SELECT * FROM PHAN_PHOI
--SELECT * FROM SAN_PHAM

--SELECT * FROM UV_SPDOITAC

/*GO
CREATE VIEW UV_PPDOITAC
AS
SELECT SP.*, CN.MACN, PP.GIA, PP.SO_LUONG_TON
FROM DOI_TAC DT JOIN TAI_KHOAN TK ON DT.MATK = TK.MATK
	 JOIN CHI_NHANH CN ON CN.MADT = DT.MADT
	 JOIN PHAN_PHOI PP ON PP.MACN = CN.MACN
	 JOIN SAN_PHAM SP ON SP.MASP = PP.MASP
WHERE TK.TENTK = CURRENT_USER --CURRENT_USER LÀ TÀI KHOẢN ĐANG ĐĂNG NHẬP 
GO

GRANT SELECT ON UV_SPDOITAC TO DOI_TAC 
SELECT * FROM PHAN_PHOI */