-- ĐỐI TÁC THÊM SẢN PHẨM --
USE QLHTChuyenHang
GO

DECLARE @FLAG INT
EXEC @FLAG = USP_DT_THEMSP 'CN000003','SP000010', 250, 10000
IF @FLAG = 1
	PRINT N'THÊM THẤT BẠI'
ELSE
	PRINT N'THÊM THÀNH CÔNG'


--SELECT * FROM UV_DHTAIXE
-- SELECT * FROM UV_TTDHTAIXE


--SELECT * FROM CHI_NHANH
--SELECT * FROM PHAN_PHOI
--SELECT * FROM UV_CN_DOITAC