USE QLHTChuyenHang
GO
-- KHÁCH HÀNG TÌM SẢN PHẨM --
DECLARE @FLAG INT
EXEC @FLAG = USP_KH_TIMSP N'Vở'
IF @FLAG = 1
	PRINT N'CÓ LỖI XẢY RA!'
ELSE
	PRINT N'HIỂN THỊ DANH SÁCH SẢN PHẨM'

-- SELECT * FROM UV_XEMSP_KH


