USE QLHTChuyenHang
GO

DECLARE @RT INT
EXEC @RT = USP_DT_CASE1_FIX N'Hoàng Thùy Linh', 'CN000001', N'30 Ngô Quyền'
IF @RT = 1
	PRINT N'CÓ LỖI XẢY RA!'
ELSE
	PRINT N'CẬP NHẬT THÔNG TIN THÀNH CÔNG'


BEGIN TRAN
SET TRAN ISOLATION LEVEL SERIALIZABLE

UPDATE UV_TTDOITAC
SET NGUOI_DAI_DIEN = N'Hoàng Thùy Linh'

UPDATE UV_CN_DOITAC
SET DUONG = N'22 Ngô Quyền'
WHERE MACN = 'CN000001'

COMMIT

SELECT * FROM UV_CN_DOITAC
SELECT * FROM UV_TTDOITAC