USE QLHTChuyenHang
GO
--ĐỐI TÁC CẬP NHẬT GIÁ MỚI CHO SẢN PHẨM --
-- 'Meg', 'TK000021'
DECLARE @FLAG INT
EXEC @FLAG = USP_DT_SUAGIA 'CN000002', 'SP000010', 8000
IF @FLAG = 1
	PRINT N'CÓ LỖI XẢY RA!'
ELSE
	PRINT N'CẬP NHẬT THÀNH CÔNG'

