USE QLHTChuyenHang
GO
--ĐỐI TÁC CẬP NHẬT GIÁ MỚI CHO SẢN PHẨM --
DECLARE @FLAG INT
EXEC @FLAG = USP_DT_SUAGIA 'CN000002', 'SP000010', 15000
IF @FLAG = 1
	PRINT N'CÓ LỖI XẢY RA!'
ELSE
	PRINT N'CẬP NHẬT THÀNH CÔNG'

