USE QLHTChuyenHang
GO
DECLARE @RT INT
EXEC @RT = USP_DT_CASE2_FIX N'Trần Thanh An', 'CN000001', N'20 Ngô Quyền'
IF @RT = 1
	PRINT N'CÓ LỖI XẢY RA!'
ELSE
	PRINT N'CẬP NHẬT THÔNG TIN THÀNH CÔNG'



BEGIN TRAN
SET TRAN ISOLATION LEVEL SERIALIZABLE

UPDATE UV_CN_DOITAC
SET DUONG = N'22 Ngô Quyền'
WHERE MACN = 'CN000001'

UPDATE UV_TTDOITAC
SET NGUOI_DAI_DIEN = N'Trần Thanh Anh'

COMMIT