USE QLHTChuyenHang
GO
-- 'Meg', 'TK000021'
DECLARE @RT INT
EXEC @RT = USP_DT_CASE1_FIX N'Hoàng Thùy Linh', 'CN000001', N'30 Ngô Quyền'
IF @RT = 1
	PRINT N'CÓ LỖI XẢY RA!'
ELSE
	PRINT N'CẬP NHẬT THÔNG TIN THÀNH CÔNG'

