USE QLHTChuyenHang
GO
-- KHÁCH HÀNG KIỂM TRA THÀNH TIỀN CỦA SẢN PHẨM
CREATE PROC USP_KH_CTDH
	@MaSP CHAR(8),
	@MaCN CHAR(8),
	@SoLuong INT
AS
BEGIN TRAN
	BEGIN TRY
	IF @MaSP NOT IN (SELECT MASP FROM SAN_PHAM)
	BEGIN
		PRINT @MaSP + N' không tồn tại!!'
		ROLLBACK TRAN
		RETURN 1
	END
	IF @MaCN NOT IN (SELECT MACN FROM PHAN_PHOI)
	BEGIN
		PRINT @MaCN + N' không tồn tại / chưa ký hợp đồng!!'
		ROLLBACK TRAN
		RETURN 1
	END

	SELECT MASP, TENSP, @SoLuong AS SO_LUONG_MUA, GIA AS DON_GIA
	FROM UV_XEMSP_KH
	WHERE MASP = @MaSP AND MACN = @MaCN
	
	WAITFOR DELAY '0:0:05'

	SELECT GIA * @SoLuong AS THANH_TIEN
	FROM UV_XEMSP_KH
	WHERE MASP = @MaSP AND MACN = @MaCN

	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG ' + ERROR_MESSAGE()
		ROLLBACK TRAN
		RETURN 1	
	END CATCH
COMMIT TRAN
RETURN 0

GO
-- ĐỐI TÁC CẤP NHẬT GIÁ MỚI CHO SẢN PHẨM
CREATE PROC USP_DT_SUAGIA
	@MaCN CHAR(8),
	@MaSP CHAR(8),
	@GiaMoi MONEY
AS
--SET TRAN ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	BEGIN TRY
		IF @MaSP NOT IN (SELECT MASP
						FROM SAN_PHAM)
		BEGIN
			PRINT @MaSP + N' không tồn tại!!'
			ROLLBACK TRAN
			RETURN 1
		END
		IF @MaCN NOT IN (SELECT MACN
						FROM UV_CN_DOITAC
						WHERE MAHD IS NOT NULL)
		BEGIN
			PRINT @MaCN + N' không tồn tại / không thuộc quản lý của đối tác / chưa được ký hợp đồng!!'
			ROLLBACK TRAN
			RETURN 1
		END

		UPDATE UV_SPDOITAC SET GIA = @GiaMoi WHERE MASP = @MaSP AND MACN = @MaCN
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG ' + ERROR_MESSAGE()
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
