USE QLHTChuyenHang

GO
--KHÁCH ĐẶT HÀNG = THÊM CÁC CHI TIẾT HÓA ĐƠN
CREATE
--ALTER
PROC USP_THEMCTDH
	@MADH CHAR(8),
	@MASP CHAR(8),
	@MACN CHAR(8),
	@SO_LUONG INT
AS
BEGIN TRAN
	BEGIN TRY

	IF NOT EXISTS (SELECT * 
				FROM UV_XEMSP_KH
				WHERE MASP = @MASP AND MACN = @MACN )
	BEGIN
		PRINT N'SẢN PHẨM KHÔNG CÓ Ở CHI NHÁNH NÀY'
		ROLLBACK TRAN
		RETURN 1
	END

	IF @SO_LUONG <= 0 
	BEGIN
		PRINT N'SỐ LƯỢNG PHẢI LỚN HƠN 0'
		ROLLBACK TRAN
		RETURN 1
	END

	DECLARE @SLT INT
	SET @SLT = (SELECT SO_LUONG_TON 
	            FROM PHAN_PHOI
				WHERE MASP = @MASP AND MACN = @MACN)
	IF @SLT < @SO_LUONG
	BEGIN
		PRINT N'SỐ LƯỢNG TỒN KHÔNG ĐỦ'
		ROLLBACK TRAN
		RETURN 1
	END

	--FOR TEST
	WAITFOR DELAY '0:0:05'
	-------------
	INSERT dbo.CHI_TIET_DON_HANG(MADH, MASP, SO_LUONG) VALUES (@MADH, @MASP, @SO_LUONG)

	UPDATE PHAN_PHOI
	SET SO_LUONG_TON = @SLT - @SO_LUONG
	WHERE MASP = @MASP AND MACN = @MACN

	END TRY

	BEGIN CATCH
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN 1	
	END CATCH

COMMIT TRAN
RETURN 0

GO
--ĐỐI TÁC NHẬP HÀNG -> THÊM SỐ LƯỢNG TỒN
CREATE
--ALTER
PROC USP_THEMSLSP
	@MASP CHAR(8),
	@MACN CHAR(8),
	@SO_LUONG INT
AS
BEGIN TRAN
	BEGIN TRY

	IF NOT EXISTS (SELECT * 
				FROM UV_SPDOITAC
				WHERE MASP = @MASP AND MACN = @MACN )
	BEGIN
		PRINT N'SẢN PHẨM KHÔNG CÓ Ở CHI NHÁNH NÀY'
		ROLLBACK TRAN
		RETURN 1
	END

	IF @SO_LUONG <= 0 
	BEGIN
		PRINT N'SỐ LƯỢNG PHẢI LỚN HƠN 0'
		ROLLBACK TRAN
		RETURN 1
	END

	DECLARE @SLT INT
	SET @SLT = (SELECT SO_LUONG_TON 
	            FROM PHAN_PHOI
				WHERE MASP = @MASP AND MACN = @MACN)

	WAITFOR DELAY '0:0:05'
	
	UPDATE PHAN_PHOI
	SET SO_LUONG_TON = @SLT + @SO_LUONG
	WHERE MASP = @MASP AND MACN = @MACN

	END TRY

	BEGIN CATCH
		DECLARE @ErrorMsg VARCHAR(2000)
		SELECT @ErrorMsg = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ErrorMsg, 16,1)
		ROLLBACK TRAN
		RETURN 1	
	END CATCH

COMMIT TRAN
RETURN 0