USE QLHTChuyenHang
GO
--TK: Kath
--Pass: TK000015
DECLARE @FLAG INT
EXEC @FLAG = USP_THEMPHIEUGIAOHANGTX 'DH000012', '2019-12-10'
IF @FLAG = 0
	PRINT N'THÊM PHIẾU GIAO HÀNG THẤT BẠI'
ELSE
	PRINT N'THÊM PHIẾU GIAO HÀNG THÀNH CÔNG'
GO