create database QLHTChuyenHang
go

use QLHTChuyenHang
go

CREATE TABLE TAI_KHOAN (
	MATK CHAR(8),
	TENTK NVARCHAR(30) UNIQUE,
	MAT_KHAU VARCHAR(20),
	EMAIL VARCHAR(50),
	SDT VARCHAR(12),
	DIA_CHI NVARCHAR(100),
	VAI_TRO NVARCHAR(20),
	TRANG_THAI NVARCHAR(25),
	CONSTRAINT PK_TAI_KHOAN PRIMARY KEY(MATK)
)
GO

CREATE TABLE HANG_HOA (
	MALH CHAR(8),
	TEN_LH NVARCHAR(50),
	CONSTRAINT PK_HANG_HOA PRIMARY KEY(MALH)
)
GO

CREATE TABLE DOI_TAC (
	MADT CHAR(8),
	MATK CHAR(8),
	TEN_DOI_TAC NVARCHAR(50) UNIQUE,
	NGUOI_DAI_DIEN NVARCHAR(30),
	THANH_PHO NVARCHAR(20),
	QUAN NVARCHAR(20),
	SO_CHI_NHANH INT,
	MALH CHAR(8),
	SO_LUONG_DON INT,
	CONSTRAINT SO_CN_CHECK CHECK (SO_CHI_NHANH > 0),
	CONSTRAINT SO_DON_CHECK CHECK (SO_LUONG_DON > 0),
	CONSTRAINT FK_DT_TK FOREIGN KEY(MATK) REFERENCES TAI_KHOAN(MATK),
	CONSTRAINT FK_DT_LH FOREIGN KEY(MALH) REFERENCES HANG_HOA(MALH),
	CONSTRAINT PK_DOI_TAC PRIMARY KEY(MADT)
)

GO
CREATE TABLE HOP_DONG (
	MAHD CHAR(8),
	MADT CHAR(8),
	THOI_GIAN_HIEU_LUC DATE,
	SO_CHI_NHANH_DK INT,
	MA_SO_THUE VARCHAR(20) UNIQUE,
	HOA_HONG DEC(5,4) CHECK (HOA_HONG BETWEEN 0 AND 1),
	
	CONSTRAINT FK_HD_DT FOREIGN KEY(MADT) REFERENCES DOI_TAC(MADT),
	CONSTRAINT PK_HOP_DONG PRIMARY KEY(MAHD)
)

GO
CREATE TABLE LICH_SU_HOP_DONG (
	MAHD CHAR(8),
	STT INT,
	THOI_GIAN_HIEU_LUC DATE,
	CONSTRAINT PK_LS_HOP_DONG PRIMARY KEY(MAHD, STT),
	CONSTRAINT FK_LS_HD FOREIGN KEY(MAHD) REFERENCES HOP_DONG(MAHD),
)

GO

CREATE TABLE CHI_NHANH (
	MACN CHAR(8),
	MADT CHAR(8),
	MAHD CHAR(8),
	DIA_CHI NVARCHAR(100),
	CONSTRAINT FK_CN_DT FOREIGN KEY(MADT) REFERENCES DOI_TAC(MADT),
	CONSTRAINT FK_CN_HD FOREIGN KEY(MAHD) REFERENCES HOP_DONG(MAHD),
	CONSTRAINT PK_CHI_NHANH PRIMARY KEY(MACN)
)


CREATE TABLE TAI_XE (
	MATX CHAR(8),
	HO_TEN NVARCHAR(100),
	CMND VARCHAR(12) NOT NULL UNIQUE,
	PHI_THUE_CHAN MONEY CHECK(PHI_THUE_CHAN >= 0),
	STK VARCHAR(20),
	BIEN_SO VARCHAR(10) NOT NULL,
	MATK CHAR(8),

	CONSTRAINT PK_MA_TAI_XE PRIMARY KEY(MATX),
	CONSTRAINT FK_TKHOAN_TXE FOREIGN KEY(MATK) REFERENCES TAI_KHOAN(MATK)
)
GO 


CREATE TABLE KHU_VUC_HOAT_DONG (
	MAKV CHAR(8),
	TENKV NVARCHAR(100),

	CONSTRAINT PK_MA_KHU_VUC PRIMARY KEY(MAKV)
)
GO

CREATE TABLE HOAT_DONG (
	MAKV CHAR(8),
	MATX CHAR(8),
	
	CONSTRAINT PK_TXE_KVUC PRIMARY KEY(MAKV, MATX),
	CONSTRAINT FK_HD_KVHD FOREIGN KEY(MAKV) REFERENCES KHU_VUC_HOAT_DONG(MAKV),
	CONSTRAINT FK_HD_TXE FOREIGN KEY(MATX) REFERENCES TAI_xE(MATX)
)
GO

CREATE TABLE KHACH_HANG (
	MAKH CHAR(8),
	HO_TEN NVARCHAR(100),
	MATK CHAR(8),

	CONSTRAINT PK_KH PRIMARY KEY(MAKH),
	CONSTRAINT FK_KH_TK FOREIGN KEY(MATK) REFERENCES TAI_KHOAN(MATK)
)
GO

CREATE TABLE DON_HANG (
	MADH CHAR(8),
	MAKH CHAR(8),	
	MADT CHAR(8),
	PHI_SAN_PHAM MONEY CHECK (PHI_SAN_PHAM > 0),
	PHI_VAN_CHUYEN MONEY CHECK (PHI_VAN_CHUYEN >= 0),
	PHI_GIAM MONEY CHECK (PHI_GIAM >= 0),
	TONG_PHI MONEY CHECK (TONG_PHI >= 0),
	TRANG_THAI NVARCHAR(20) CHECK(TRANG_THAI IN (N'Chưa xác nhận', N'Đã xác nhận', N'Đang giao hàng', N'Đã giao hàng', N'Đã hủy')),
	HINH_THUC_THANH_TOAN NVARCHAR(30) CHECK(HINH_THUC_THANH_TOAN IN (N'Thanh toán khi nhận hàng', N'Thẻ tín dụng/Thẻ ghi nợ', N'Tài khoản Ngân hàng liên kết')),
	DIA_CHI_GIAO_HANG NVARCHAR(50),
	
	PRIMARY KEY(MADH),
	CONSTRAINT FK_DHANG_KHHANG FOREIGN KEY(MAKH) REFERENCES KHACH_HANG(MAKH),
	CONSTRAINT FK_DHANG_DOITAC FOREIGN KEY(MADT) REFERENCES DOI_TAC(MADT)
)
GO

CREATE TABLE TRANG_THAI_DON_HANG (
	TEN_TRANG_THAI NVARCHAR(20) CHECK(TEN_TRANG_THAI IN (N'Chưa xác nhận', N'Đã xác nhận', N'Đang giao hàng', N'Đã giao hàng', N'Đã hủy')),
	MADH CHAR(8),
	THOI_GIAN DATE
	CONSTRAINT PK_TRANG_THAI PRIMARY KEY(TEN_TRANG_THAI, MADH)
	CONSTRAINT FK_TT_DH FOREIGN KEY(MADH) REFERENCES DON_HANG(MADH)
)
GO

CREATE TABLE PHIEU_GIAO_HANG (
	MATX CHAR(8),
	MADH CHAR(8),
	NGAY_GIAO DATE NOT NULL,
	
	CONSTRAINT PK_TXE_DHANG PRIMARY KEY(MATX, MADH),
	CONSTRAINT FK_TXE_PGHANG FOREIGN KEY(MATX) REFERENCES TAI_XE(MATX),
	CONSTRAINT FK_DH_PGHANG FOREIGN KEY(MADH) REFERENCES DON_HANG(MADH)
)

GO

CREATE TABLE SAN_PHAM (
	MASP CHAR(8),
	TENSP NVARCHAR(100),
	SO_LUONG_TON INT CHECK(SO_LUONG_TON >= 0),
	MO_TA NVARCHAR(500),
	GIA MONEY CHECK (GIA > 0),
	
	CONSTRAINT PK_SP PRIMARY KEY(MASP)
)

GO

CREATE TABLE PHAN_PHOI (
	MASP CHAR(8),
	MACN CHAR(8),

	CONSTRAINT PK_PPHOI PRIMARY KEY(MASP, MACN),
	CONSTRAINT FK_SP_PPHOI FOREIGN KEY(MASP) REFERENCES SAN_PHAM(MASP),
	CONSTRAINT FK_CN_PPHOI FOREIGN KEY(MACN) REFERENCES CHI_NHANH(MACN)
)
GO

CREATE TABLE CHI_TIET_DON_HANG (
	MADH CHAR(8),
	MASP CHAR(8),	
	SO_LUONG INT CHECK(SO_LUONG > 0),
	THANH_TIEN MONEY CHECK (THANH_TIEN > 0),
	
	PRIMARY KEY(MADH, MASP),
	CONSTRAINT FK_CTDHANG_DHANG FOREIGN KEY(MADH) REFERENCES DON_HANG(MADH),
	CONSTRAINT FK_CTDHANG_SANPHAM FOREIGN KEY(MASP) REFERENCES SAN_PHAM(MASP)
)