USE QLHTChuyenHang
GO

--TRIGGER TRÊN BẢNG DON_HANG CHO VIEC SUA
CREATE TRIGGER TG_TONGPHI_FOR_UPDATE_DONHANG
ON DON_HANG FOR UPDATE
AS
BEGIN
	IF EXISTS(SELECT * FROM inserted
				WHERE inserted.PHI_GIAM > inserted.PHI_VAN_CHUYEN + inserted.PHI_SAN_PHAM)
		BEGIN
			PRINT(N'Giá giảm không được vượt quá tổng giá bán và phí vận chuyển!')
			ROLLBACK
		END

	UPDATE DON_HANG
	SET DON_HANG.TONG_PHI = DON_HANG.PHI_SAN_PHAM + DON_HANG.PHI_VAN_CHUYEN - DON_HANG.PHI_GIAM
	WHERE DON_HANG.MADH IN (SELECT DISTINCT inserted.MADH FROM inserted)
END
GO

--TRIGGER TRÊN BẢNG CHI_TIET_DON_HANG CHO VIEC THEM SUA
CREATE TRIGGER TG_THANHTIEN_FOR_INSERT_UPDATE_CTHD
ON CHI_TIET_DON_HANG FOR UPDATE, INSERT
AS
BEGIN
	UPDATE CHI_TIET_DON_HANG
	SET CHI_TIET_DON_HANG.THANH_TIEN = (SELECT SP.GIA * CTDH.SO_LUONG
										FROM SAN_PHAM SP
										WHERE SP.MASP = CTDH.MASP
										)
	FROM CHI_TIET_DON_HANG CTDH
	JOIN inserted ON inserted.MADH = CTDH.MADH AND inserted.MASP = CTDH.MASP
	
	UPDATE DON_HANG
	SET DON_HANG.PHI_SAN_PHAM = (SELECT SUM(CTDH.THANH_TIEN)
								FROM CHI_TIET_DON_HANG CTDH
								WHERE CTDH.MADH = DON_HANG.MADH
								GROUP BY CTDH.MADH
								)
	WHERE DON_HANG.MADH IN (SELECT DISTINCT inserted.MADH FROM inserted)
	
	-- Gọi trigger update tổng phí trên bảng DON_HANG
	UPDATE DON_HANG
	SET DON_HANG.TONG_PHI = 0 
	WHERE DON_HANG.MADH IN (SELECT DISTINCT inserted.MADH FROM inserted)
END
GO

--TRIGGER TRÊN BẢNG CHI_TIET_DON_HANG CHO VIEC XÓA
CREATE TRIGGER TG_TONGPHI_FOR_DELETE_CTDH
ON CHI_TIET_DON_HANG FOR DELETE
AS
BEGIN
	UPDATE DON_HANG
	SET DON_HANG.PHI_SAN_PHAM -= (SELECT SUM(deleted.THANH_TIEN)
							FROM deleted
							WHERE DON_HANG.MADH = deleted.MADH
							GROUP BY deleted.MADH
							)
	WHERE DON_HANG.MADH IN (SELECT DISTINCT MADH FROM deleted)
END
GO

--TRIGGER TRÊN BẢNG CHI_TIET_DON_HANG CHO VIEC XÓA
CREATE TRIGGER TG_FOR_INSERT_UPDATE_TTDH
ON TRANG_THAI_DON_HANG FOR UPDATE, INSERT
AS
BEGIN
	IF EXISTS(SELECT * FROM inserted 
				WHERE inserted.THOI_GIAN <= (SELECT MAX(TTDH.THOI_GIAN)
													FROM TRANG_THAI_DON_HANG TTDH
													WHERE inserted.MADH = TTDH.MADH)
				)
		BEGIN
			PRINT(N'Thời gian của trạng thái mới không hợp lệ!')
			ROLLBACK
		END
END
GO

UPDATE DON_HANG
SET TONG_PHI = 0
GO

INSERT CHI_TIET_DON_HANG VALUES('DH000000', 'SP000001', 2, 50000)
GO

DELETE FROM CHI_TIET_DON_HANG WHERE (MADH = 'DH000000' AND MASP = 'SP000001')
GO

SELECT TOP 20 *
FROM SAN_PHAM
GO

SELECT TOP 20 *
FROM CHI_TIET_DON_HANG
GO

SELECT TOP 20 *
FROM DON_HANG
GO

UPDATE TRANG_THAI_DON_HANG
SET THOI_GIAN = '2021-01-14' WHERE MADH = 'DH000004' AND TEN_TRANG_THAI = N'Đã hủy'
GO

INSERT TRANG_THAI_DON_HANG VALUES (N'Đã hủy', 'DH000201','2021-01-09')
GO

SELECT *
FROM TRANG_THAI_DON_HANG TT
WHERE TT.MADH = 'DH000201'
GO